### ISSUE TITLE
大兄弟你的项目报错了， 安装完依赖，运行npm run dev，控制台报错

### ISSUE THREAD

**Issue by skique** [jiangshanmeta/vue-admin#1]
![image](https://user-images.githubusercontent.com/17895803/45194943-ecebb700-b287-11e8-89c9-24dbbb97f722.png)

**Comment by jiangshanmeta** [comment]
@skique    我download zip 然后 npm install  然后 sudo npm run dev 没问题

node版本 8.11.3 npm 版本 6.1.0 

再装一次依赖试试？

**Comment by skique** [comment]
我把node和npm都同步到你相同的版本，再重新安装再运行还是一样报错， 我是windows平台

**Comment by jiangshanmeta** [comment]
@skique   window8 node v 8.9.0  npm v 5.5.1  没重复出问题  我一会同步一下node和npm版本试试

**Comment by jiangshanmeta** [comment]
@skique   win8 64位   node 8.11.3  npm 6.1.0  最新zip包没重现出问题

**Comment by jiangshanmeta** [comment]
@skique  现在行了不。我windows和ubuntu都重现不出截图的问题。
